#!/usr/bin/env bash
# Concatenates every migration into supabase/hosted-setup.sql, for projects where
# the CLI cannot be linked (wrong account, no database password) and the SQL Editor
# is the only way in. Keep this in step with supabase/migrations/.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=supabase/hosted-setup.sql
{
  echo "-- Generated by npm run db:bundle — do not edit by hand."
  echo "-- All migrations, in order. Paste into the Supabase SQL Editor and Run."
  echo ""
  for f in supabase/migrations/*.sql; do
    printf '\n-- ═══ %s ═══\n\n' "$(basename "$f")"
    cat "$f"
  done
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
